name: nutrisalud
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flip_card: ^0.7.0
  page_view_dot_indicator: ^2.3.0
  font_awesome_flutter: ^10.7.0
  introduction_screen: ^3.1.12
  url_launcher: ^6.1.10
  flutter_native_splash: ^2.2.9
  flutter_svg: ^1.0.3
  http: ^0.13.5
  shared_preferences: ^2.2.2
  get: ^4.6.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  android: true
  color: "#F5F5F5"
  image: "assets/imgs/splashNutrisalud.png"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/imgs/launcherIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/imgs/
    - assets/imgs/IntroductionImages/
    - assets/svgs/
