import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'core/constants/app_constants.dart';
import 'core/routing/app_router.dart';
import 'core/services/notification_service.dart';
import 'core/storage/key_value_store.dart';
import 'core/themes/app_theme.dart';
import 'features/settings/data/settings_controller.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Attempt Firebase init. Falls back to NoopNotificationService when
  // firebase_options.dart has not yet been generated by `flutterfire configure`.
  NotificationService notificationService = const NoopNotificationService();
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    notificationService = FcmNotificationService();
  } on UnsupportedError {
    debugPrint(
      '[FCM] firebase_options.dart not configured — '
      'push notifications disabled. Run `flutterfire configure` to enable.',
    );
  } catch (e) {
    debugPrint('[FCM] Firebase init error: $e');
  }

  final prefs = await SharedPreferences.getInstance();

  runApp(
    ProviderScope(
      overrides: [
        keyValueStoreProvider.overrideWithValue(SharedPreferencesStore(prefs)),
        notificationServiceProvider.overrideWithValue(notificationService),
      ],
      child: const NutriSaludApp(),
    ),
  );
}

class NutriSaludApp extends ConsumerStatefulWidget {
  const NutriSaludApp({super.key});

  @override
  ConsumerState<NutriSaludApp> createState() => _NutriSaludAppState();
}

class _NutriSaludAppState extends ConsumerState<NutriSaludApp> {
  @override
  void initState() {
    super.initState();
    // Fire-and-forget: requests permission, gets FCM token, sets up listeners.
    ref.read(notificationServiceProvider).initialize();
  }

  @override
  Widget build(BuildContext context) {
    final router = ref.watch(appRouterProvider);
    final themeMode = ref.watch(themeModeProvider);

    return MaterialApp.router(
      title: AppConstants.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: themeMode,
      routerConfig: router,
    );
  }
}
